spring.application.name=ZymProductsOrderingProject

spring.datasource.url=jdbc:postgresql://localhost:5432/ecart
spring.datasource.username=postgres
spring.datasource.password=Aripaka@1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

# Disable default static resource handler to prevent NoResourceFoundException
# for PUT/DELETE/PATCH requests. Uploads are served via WebConfig resource handler.
spring.web.resources.add-mappings=false


razorpay.key=rzp_live_SfPj8SfZggPOsI
razorpay.secret=XxzCTOWNX3sBMCvaR5gKOneV

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=udaykumararipaka@gmail.com
spring.mail.password=oicp ivnd kpuv ezzb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

file.upload-dir=uploads

# Secret key for signing JWTs (must be long enough, at least 32 chars)
jwt.secret=Qk9hZ3pXc2p5RkZqU2hYd1h5ZkRrVnNqR3p0cE5uY1dQd1pYd3h0U2p5RkZqU2hYd1h5ZkRrVnM=

# Expiration in milliseconds (e.g. 1 day = 86400000)
jwt.expiration-ms=86400000


fast2sms.api.key=kJZznWcqx9Ym6w5PKgOesAyVlaMDGpTt0Cb1h28RiIQfUSN3F4CUEPgAsn5uwQLzGIlXKZY263VhD7rF
